### ISSUE TITLE
Different braces in grammar

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/normalizer#14]
I found inconsistency between canonical phi-calculus grammar (on the pic) and grammar in https://github.com/objectionary/normalizer/blob/master/eo-phi-normalizer/grammar/EO/Phi/Syntax.cf. 
Rules `program`, `formation` and `application` must have different braces
![photo_2023-12-28 17 38 08](https://github.com/objectionary/normalizer/assets/37025995/2a613cf6-56e6-4271-9614-c7f3c1f2f339)

**Comment by aabounegm** [comment]
Just to confirm: `Program` should remain `{}`, `Formation` should use `⟦⟧`, and `Application` should use `()`, correct?
I'm only asking because `Program` in the screenshot above has no brackets around `<Object>`, but in [Phi.g4](https://github.com/objectionary/eo/blob/fa24c7cc47e1ac473fb930f3a08ccc4d88d9d1e3/eo-parser/src/main/antlr4/org/eolang/parser/Phi.g4) it specifies `{}`
